spring.application.name=activitytracker
server.port=2020

#tell spring to wait to run data.sql until after tables are created
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true